<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>async函数</title>
</head>
<body>
  
</body>
<script>
  /* 
    async函数
      1. 函数的返回值为promise对象
      2. promise对象的结果由async函数执行的返回值决定
  */

 async function main() {
  // 1.如果返回值是一个非promise类型的数据，那返回的结果是一个成功的promise对象
  // return '123'   // 返回成功的promise对象 PromiseState："fulfilled" PromiseResult: "123"

  // 2.如果返回值是一个promise对象，那返回的结果跟这个promise的结果有关
  return new Promise((resolve, reject)=>{
    resolve('Success')  // 返回成功的promise对象 PromiseState："fulfilled" PromiseResult: "Success"
    // reject('Error')     // 返回失败的promise对象 PromiseState："rejected" PromiseResult: "Error"
  })
 }
 let result = main();
//  console.log(result)  


 /* 
  await表达式
    1. await右侧的表达式一般为promise对象，但也可以是其他的值
    2. 如果表达式是promise对象，await返回的是promise成功的值
    3. 如果表达式是其它值，直接将此值作为await的返回值
  
  注意：
    1. await表达式必须写在async函数中，但async函数中可以没有await
    2. 如果await的promise失败了，就会抛出异常，需要通过try...catch捕获处理
 */

 async function main2() {
  let p = new Promise((resolve, reject)=>{
    // resolve('OK')
    reject('Error') 
  })
  // 1.右侧为其它类型的数据
  // let res = await '123';  
  // console.log(res)// 123
  
  // 2.右侧为promise成功的情况
  // let res2 = await p;  
  // console.log(res2) // OK

  // 3.右侧为promise失败的情况，会抛出错误，需要通过try...catch处理
  try {
    let res3 = await p;
    console.log(res3); // Error
  } catch (error) {
    console.log(error)
  }
 }
 main2();
</script>
</html>